dist: bionic
addons:
  apt:
    packages:
      - libreadline-dev
      - libgc-dev
      - libstdc++-5-dev
      - llvm
      - clang
      - lld
      - ruby
script:
- ./bootstrap.sh
- ./runtests.sh
- ./runperf.sh
- ./run-mal-tests.sh
