#!/bin/sh
set -e

if [ -z "$1" ] ; then
  echo "Usage: $0 sourcefile.mal [outputexecutable]"
  exit 1
fi

bindir=$(dirname $0)
srcfile=$(readlink -f $1)
if [ -n "$2" ] ; then
  out="$2"
else
  out="$(dirname $srcfile)/$(basename $srcfile .mal)"
fi

cd $bindir
mal-interpreter/mal malc.mal $srcfile > $out.ll
opt -S -O3 $out.ll -o $out.opt.ll
llc -filetype=obj $out.opt.ll -o $out.o
gcc $out.o -lgc -lreadline -o $out
